language: julia
os:
  - linux
  - osx
julia:
  - 1
  #- nightly
codecov: true
sudo: required
addons:
  apt_packages:
    - gfortran
jobs:
  allow_failures:
   - julia: nightly
  include:
    - stage: "MINLPTests"
      julia: 1
      os: linux
      script:
        - julia --project=test/MINLPTests -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=test/MINLPTests --color=yes test/MINLPTests/run_minlptests.jl
      after_success: skip

