language: julia
os:
  - linux
  - osx
julia:
  - 1.5
  - nightly
codecov: true
sudo: required
addons:
  apt_packages:
    - gfortran
jobs:
  allow_failures:
   - julia: nightly
  include:
    - stage: "MINLPTests and CUTEstTests"
      julia: 1.5
      os: linux
      script:
        - julia --project=test/MINLPTests -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=test/MINLPTests --color=yes test/MINLPTests/run_minlptests.jl
        - julia --project=test/CUTEstTests -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=test/CUTEstTests --color=yes test/CUTEstTests/run_cutesttests.jl
      after_success: skip
