# METIS
[[METIS]]
arch = "i686"
git-tree-sha1 = "3bb8df8f130cfa2f754c62195e8d45e185b70f4a"
libc = "musl"
os = "linux"

[[METIS.download]]
sha256 = "afe4bf4900c5b3e0ab71205f83ccb758e0a2a73111183d04215e2993e6ec5838"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.i686-linux-musl.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "c6799eb86a9f06fca3523408ebdaffea902f69b5"
libc = "musl"
os = "linux"

[[METIS.download]]
sha256 = "ffc12804776b476f76a4005baacd894c337aa448ea0410496f4c9e882442a66c"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "45da1c3e85c743be740b119e9c454882d55c1057"
os = "windows"

[[METIS.download]]
sha256 = "7b86213cd2833d8b7320c8a9f3cec53ddf78b72e156696e570df7e1e1748bb90"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "c79c065dd80a73c7c89d1e9f60a1a14f8849be1e"
os = "windows"

[[METIS.download]]
sha256 = "8939ec73d1d27aa5d8aadf5cbaf2bad9445188fedab4c20036a634ef8f56315d"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.x86_64-w64-mingw32.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "36e3bdd501217db399c5e04d800ae5c36edd6cdb"
libc = "glibc"
os = "linux"

[[METIS.download]]
sha256 = "74f0dd9679196d6c4b0513e517aa28fc1619079493c110e6ec3d994e57df8516"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.armv7l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "dececfd251630954aafc8df205041b00861a1f6f"
libc = "musl"
os = "linux"

[[METIS.download]]
sha256 = "8844baa88bd72f80d71a5d29d64bbcce3b20f61a06b5888e761e468ded10fd08"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.armv7l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "46161f54d73be3f0e17d89c397a2142276b0cef5"
libc = "glibc"
os = "linux"

[[METIS.download]]
sha256 = "abeb28331b13f8047aa3c0fb8bc51b607e8f7039c72c095c0d14d1c911c6d51b"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "820382e6c2f6674e357232bdf4aab3b53d4b1fcd"
libc = "glibc"
os = "linux"

[[METIS.download]]
sha256 = "b470e6ac780e1266a8d703abcf68b8a3f746cdcc737bdf1558f0780a6549d9d4"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "8efbbc522c6d5cd487b67177a83850480c62cda2"
libc = "glibc"
os = "linux"

[[METIS.download]]
sha256 = "76fb068c5f594b9b6489f8d661dfbab27fd408e63f0e3422d5ea01007fea08b2"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "d5c6243ccf8d1bc26ac624fe7dba239df828e73f"
os = "macos"

[[METIS.download]]
sha256 = "aa155bac90b8929dccc94556c44f7b29bcb943af7da9f2fae462530107bee5fd"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.x86_64-apple-darwin14.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "632e487bfe44fe18d705e8db2f2953eaf30ca5de"
libc = "glibc"
os = "linux"

[[METIS.download]]
sha256 = "41e127ee4644905ddb2c6ba3e9d53ebedad09ac53380bb107041f443cae46814"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "bfe48e2bc7b0e92735799dddbf451a92e33f1dc4"
os = "freebsd"

[[METIS.download]]
sha256 = "40d6ff6085476383c99ac110174b6d49a0ea970b898991af6c731b0c08c7ed7d"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.x86_64-unknown-freebsd11.1.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "0bd5bc8040cd3ccae4f0e47de110b41a5b044056"
libc = "musl"
os = "linux"

[[METIS.download]]
sha256 = "0ded976613ba2ddd499a041807dd61707aacb1630060fe6b9315896ff385bf8e"
url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+3/METIS.v4.0.3.x86_64-linux-musl.tar.gz"