name = "cuMadNLP"
uuid = "d47ba66d-cfbe-40a6-987c-5a56a1b97d17"
version = "0.1.0"
authors = ["MadNLP contributors"]

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
CUDACore = "bd0ed864-bdfe-4181-a5ed-ce625a5fdea2"
MadCoreCUDA = "bc4e0c13-4672-410c-a012-e283a446691e"
MadCoreCUDSS = "1f78e23c-6596-4cec-b75b-391af35fa428"
MadNLPGPU = "d72a61cc-809d-412f-99be-fd81f4b8a598"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"

[sources]
MadNLP = {path = ".."}
MadCoreCUDA = {path = "../MadCore/lib/MadCoreCUDA"}
MadCoreCUDSS = {path = "../MadCore/lib/MadCoreCUDSS"}
MadNLPGPU = {path = "../MadNLPGPU"}

[compat]
Reexport = "1"
CUDACore = "6"
MadCoreCUDA = "0.1"
MadCoreCUDSS = "0.1"
MadNLPGPU = "0.11"
MadNLP = "0.11"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
