name = "MadNLPGPU"
uuid = "d72a61cc-809d-412f-99be-fd81f4b8a598"
version = "0.11.0"
authors = ["MadNLP contributors"]

[deps]
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
MadCoreKernelAbstractions = "b5d449e2-bd97-4205-9c78-f5795562dab8"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[sources]
MadNLP = {path = ".."}
MadCoreKernelAbstractions = {path = "../MadCore/lib/MadCoreKernelAbstractions"}

[compat]
GPUArraysCore = "0.2"
MadCoreKernelAbstractions = "0.1"
MadNLP = "0.11"
Reexport = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
