name: CompatHelper
on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.COMPATHELPER_PRIV }}  # optional
        run: julia -e 'using CompatHelper; CompatHelper.main(; subdirs = ["","MadCore","MadCore/lib/MadCoreLDLFactorizations","MadCore/lib/MadCoreMUMPS","MadCore/lib/MadCoreSuiteSparse","MadCore/lib/MadCoreHSL","MadCore/lib/MadCorePardiso","MadCore/lib/MadCoreKernelAbstractions","MadCore/lib/MadCoreCUDA","MadCore/lib/MadCoreAMDGPU","lib/CuMadNLP","lib/MadNLPTests"])'
